ftp:
  server: ftp://localhost:21
  username: admin
  password: mypass
  remote-input-directory: /input
  remote-archive-directory: /archive
  remote-file: /book.txt
  local-file-path: C:\Users\patryk.kawula\IdeaProjects\task_crud\temporary
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;database=taskdb;trustServerCertificate=true
    url: jdbc:sqlserver://host.docker.internal:1433;database=taskdb;trustServerCertificate=true
    username: dbu_jenkins
    password: dbu_jenkins
  application:
    name: task_crud
  jpa:
    hibernate:
      ddl-auto: validate
  amqp:
    deserialization:
      trust:
        all
